# history
shopt -s histappend
shopt -s histverify
HISTSIZE=102400
HISTTIMEFORMAT='%Y/%m/%d %H:%M:%S '
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# grep
alias grep='grep --color=always'

# docker
alias kill-docker-all='if [ -n "`docker ps -q`" ]; then docker kill `docker ps -q`; fi'
